<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()) : ?>
    <div class="block widget block-special-products-images">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Special Offers')) ?></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-special-products-<?= $block->escapeHtmlAttr($suffix) ?>" 
                class="product-items product-items-images">
                <?php foreach ($_products->getItems() as $_product) : ?>
                    <li class="product-item">
                        <a class="product-item-photo" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                           title="<?= /* @noEscape */ $block->stripTags($_product->getName(), null, true) ?>">
                            <?php /* special_products_images_only_widget */ ?>
                            <?= $block->getImage($_product, 'new_products_images_only_widget')->toHtml() ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ol>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
